<?php

namespace ContainerTHmBDlK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O8oKgvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._o8oKgv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._o8oKgv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entreprise' => ['privates', '.errored..service_locator._o8oKgv.App\\Entity\\Entreprise', NULL, 'Cannot autowire service ".service_locator._o8oKgv": it references class "App\\Entity\\Entreprise" but no such service exists.'],
        ], [
            'entreprise' => 'App\\Entity\\Entreprise',
        ]);
    }
}
