<?php

namespace Container3BGMDQK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LqWjlogService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LqWjlog' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LqWjlog'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'entreprise' => ['privates', '.errored..service_locator.LqWjlog.App\\Entity\\Entreprise', NULL, 'Cannot autowire service ".service_locator.LqWjlog": it references class "App\\Entity\\Entreprise" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'entreprise' => 'App\\Entity\\Entreprise',
        ]);
    }
}
