<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXtGD5jx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXtGD5jx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXtGD5jx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXtGD5jx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXtGD5jx\App_KernelDevDebugContainer([
    'container.build_hash' => 'XtGD5jx',
    'container.build_id' => '1124b389',
    'container.build_time' => 1669645715,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXtGD5jx');
