<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW1Y4CTm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW1Y4CTm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW1Y4CTm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW1Y4CTm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW1Y4CTm\App_KernelDevDebugContainer([
    'container.build_hash' => 'W1Y4CTm',
    'container.build_id' => 'd76fe52c',
    'container.build_time' => 1669668553,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW1Y4CTm');
