<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7peMHxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7peMHxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7peMHxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7peMHxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7peMHxC\App_KernelDevDebugContainer([
    'container.build_hash' => '7peMHxC',
    'container.build_id' => '3e24c252',
    'container.build_time' => 1669634207,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7peMHxC');
